### ISSUE TITLE
App has no method 'configure'

### ISSUE THREAD

**Issue by petre2dor** [scotch-io/starter-node-angular#1]
`$ node server.js`               

`.......starter-node-angular/server.js:14
app.configure(function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/..../starter-node-angular/server.js:14:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`

**Comment by chris-sev** [comment]
This was caused since the `package.json` file used the `latest` version of express. This brought in version 4.0 instead of the 3.x this was designed for.

I've set up the package.json to call the specific version so it works now. Just install your node modules again.

I'll update this to 4.0 in the future after it's officially out.

Thanks.

**Comment by petre2dor** [comment]
cool. thanks a lot!
