### ISSUE TITLE
html content is not showing 

### ISSUE THREAD

**Issue by mokubor** [scotch-io/starter-node-angular#15]
Thanks for the tutorial. 
I followed all the steps there and also compared my file with the github repo. 
On all routes, '/',  '/nerds' or '/geeks' routes are called there is no  tagline and other *.html output/text do not appear . I downloaded the repository straight from git and ran it and it worked. I used a tool to find differences in the files and other than extra empty lines, there were no differences. What could I have done wrong?

**Comment by mokubor** [comment]
This is the error message I found when exploring with google chromes developer tools 

`Failed to instantiate module sampleApp due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.6.3/$injector/modulerr?p0=N...)
    at http://localhost:3040/libs/angular/angular.min.js:6:425
    at http://localhost:3040/libs/angular/angular.min.js:42:407
    at p (http://localhost:3040/libs/angular/angular.min.js:7:495)
    at g (http://localhost:3040/libs/angular/angular.min.js:41:476)
    at http://localhost:3040/libs/angular/angular.min.js:42:149
    at p (http://localhost:3040/libs/angular/angular.min.js:7:495)
    at g (http://localhost:3040/libs/angular/angular.min.js:41:476)
    at eb (http://localhost:3040/libs/angular/angular.min.js:46:44)
    at c (http://localhost:3040/libs/angular/angular.min.js:21:373)
    at Pc (http://localhost:3040/libs/angular/angular.min.js:22:179
`
